on:
  workflow_dispatch:
  push:
    branches:
    - staging

name: Auto-Deploy Dev-Build / staging ðŸš€
jobs:
  web-deploy:
    name: Dev-Build Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Installing packages
      run: npm install --legacy-peer-deps
      
    - name: Build Project
      run: npm run dev-build-deploy
    
    - name: Deploying to the server
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ventura.ftp.tools
        username: ventura_team
        password: ${{ secrets.DEV_PASSWORD }}
        
        local-dir: ./dist/
        server-dir: ./2022/unnamed_project/        
        
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
